# pre-commit hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: check-ast
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: double-quote-string-fixer

# trailing comma fixer
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.4.0
  hooks:
  - id: add-trailing-comma

# black formatter
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    args: [--config, pyproject.toml]

# yaml formatter
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

# import cleaner
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.3
  hooks:
  - id: pycln
    args: [--config, pyproject.toml]

# import sorter
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: \.(py)$
    args: [--settings-path, pyproject.toml]

# docstring style checker
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml, tomli]
    args: [--config, pyproject.toml]

# static type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    args: [--config-file, pyproject.toml]
