[tool.black]
line_length = 100
skip_string_normalization = true

[tool.pycln]
all = true

[tool.isort]
line_length = 100
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true

[tool.pydocstyle]
convention = 'google'
add_ignore = 'D100, D102, D103, D104, D105, D106, D107'

[tool.mypy]
install_types = true
no_strict_optional = true
ignore_missing_imports = true
